// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kind
{
    [KindResourceType("kind:index:Kind")]
    public partial class Kind : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the KinD cluster.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a Kind resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Kind(string name, KindArgs args, CustomResourceOptions? options = null)
            : base("kind:index:Kind", name, args ?? new KindArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Kind(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kind:index:Kind", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Kind resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Kind Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Kind(name, id, options);
        }
    }

    public sealed class KindArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the KinD cluster.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public KindArgs()
        {
        }
        public static new KindArgs Empty => new KindArgs();
    }
}
