name: test

on:
  workflow_dispatch:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/pulumi/devcontainer:latest
      options: --user root
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4
      id: git
      with:
        submodules: 'recursive'
    -
      name: Unshallow clone for tags
      id: tags
      run: |
        set -ex
        sudo chown -R $(whoami) /__w/pulumi-kind-native/pulumi-kind-native
        git config --global --add safe.directory /__w/pulumi-kind-native/pulumi-kind-native
        git fetch --prune --unshallow --tags
    -
      name: Build
      id: build
      run: |
        set -ex
        git config --global --add safe.directory /__w/pulumi-kind-native/pulumi-kind-native
        pwd
        ls -lah
        git status
        git branch -a
        pulumictl get version --is-prerelease --debug --version-prefix 0.0.1
        make build
    -
      name: Install
      id: install
      run: |
        set -ex
        make install
    -
      name: Generate multi-language examples from yaml IaC program
      id: generate-examples
      run: |
        set -ex
        make examples
