name: test

on:
  workflow_dispatch:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/pulumi/devcontainer:latest
      options: --user vscode
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
    -
      name: Adjust UID for GitHub Actions
      run: |
        # Adjust the UID of the 'vscode' user to 1001 and GID if necessary
        sudo usermod -u 1001 vscode
        sudo groupmod -g 1001 vscode
        # Ensure the vscode user owns their home directory
        sudo chown -R vscode:vscode /home/vscode
        # Ensure the vscode user has the right permissions on the working directories
        sudo chown -R vscode:vscode /__w/
    -
      name: Checkout repository
      uses: actions/checkout@v4
      id: git
      with:
        submodules: 'recursive'
    -
      name: Build and install
      id: build
      run: |
        make build
    -
      name: Build and install
      id: install
      run: |
        make install
    -
      name: Build and install
      id: generate-examples
      run: |
        make examples
